CFLAGS=-std=c11 -g -fno-common
SRCS=$(filter-out tmp.c,$(wildcard *.c))
OBJS=$(SRCS:.c=.o)

minicc: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

$(OBJS): minicc.h

test: minicc
	./test/test.sh
	bash ./test/driver_stdin.sh
	bash ./test/driver_cli.sh
	bash ./test/line_splicing.sh
	bash ./test/digraph_punctuators.sh
	bash ./test/preprocessor.sh
	bash ./test/preprocessor_advanced.sh
	bash ./test/preprocessor_stringification_literals.sh
	bash ./test/preprocessor_inactive_branches.sh
	bash ./test/preprocessor_recursive_macros.sh
	bash ./test/preprocessor_integer_semantics.sh
	bash ./test/preprocessor_function_invocation.sh
	bash ./test/preprocessor_char_constants.sh
	bash ./test/preprocessor_include_paths.sh
	bash ./test/preprocessor_quote_include_paths.sh
	bash ./test/preprocessor_include_after_paths.sh
	bash ./test/preprocessor_nostdinc.sh
	bash ./test/preprocessor_forced_includes.sh
	bash ./test/preprocessor_dump_macros.sh
	bash ./test/preprocessor_compatibility_pack.sh
	bash ./test/preprocessor_include_next.sh
	bash ./test/preprocessor_absolute_includes.sh
	bash ./test/preprocessor_system_includes.sh
	bash ./test/preprocessor_pragma_once.sh
	bash ./test/preprocessor_pragma_operator.sh
	bash ./test/dependency_generation.sh
	bash ./test/dependency_missing_headers.sh
	bash ./test/dependency_failure_safety.sh
	bash ./test/predefined_macros.sh
	bash ./test/predefined_source_macros.sh
	bash ./test/predefined_datetime_macros.sh
	bash ./test/float.sh
	bash ./test/floating_literals.sh
	bash ./test/float_header.sh
	bash ./test/float_abi.sh
	bash ./test/float_callback_abi.sh
	bash ./test/mixed_callback_abi.sh
	bash ./test/function_return_abi.sh
	bash ./test/incomplete_tags.sh
	bash ./test/incomplete_flexible_arrays.sh
	bash ./test/flexible_array_containment.sh
	bash ./test/tag_definition_constraints.sh
	bash ./test/duplicate_record_members.sh
	bash ./test/record_static_assert.sh
	bash ./test/anonymous_record_members.sh
	bash ./test/bitfields.sh
	bash ./test/typedef_scope.sh
	bash ./test/enum_scope.sh
	bash ./test/ordinary_namespace.sh
	bash ./test/enum_constexpr_tags.sh
	bash ./test/enum_value_range.sh
	bash ./test/abi_stack_args.sh
	bash ./test/integer_parameter_abi.sh
	bash ./test/int64_abi.sh
	bash ./test/mixed_scalar_abi.sh
	bash ./test/mixed_variadic_abi.sh
	bash ./test/variadic_default_promotions.sh
	bash ./test/variadic_function_pointer_abi.sh
	bash ./test/enum_abi.sh
	bash ./test/pointer_abi.sh
	bash ./test/prototype_params.sh
	bash ./test/parameter_array_qualifiers.sh
	bash ./test/vla.sh
	bash ./test/function_pointer_prototype.sh
	bash ./test/callable_declarators.sh
	bash ./test/prototype_arity.sh
	bash ./test/recursive_declarators.sh
	bash ./test/type_names.sh
	bash ./test/type_compatibility.sh
	bash ./test/semantic_assignments.sh
	bash ./test/expression_operators.sh
	bash ./test/unary_plus.sh
	bash ./test/logical_scalar.sh
	bash ./test/comparison_scalar.sh
	bash ./test/pointer_equality.sh
	bash ./test/conditional_operator.sh
	bash ./test/null_pointer_constants.sh
	bash ./test/pointer_arithmetic.sh
	bash ./test/lvalue_semantics.sh
	bash ./test/type_qualifiers.sh
	bash ./test/restrict_qualifier.sh
	bash ./test/storage_class_specifiers.sh
	bash ./test/register_addressability.sh
	bash ./test/thread_local.sh
	bash ./test/typedef_storage_class.sh
	bash ./test/implicit_int_constraints.sh
	bash ./test/object_linkage_redeclarations.sh
	bash ./test/function_linkage_emission.sh
	bash ./test/unresolved_function_calls.sh
	bash ./test/cast_constraints.sh
	bash ./test/switch_constraints.sh
	bash ./test/nested_switch_labels.sh
	bash ./test/control_flow_context.sh
	bash ./test/control_condition_scalars.sh
	bash ./test/function_type_constraints.sh
	bash ./test/oldstyle_function_compatibility.sh
	bash ./test/arithmetic_conversions.sh
	bash ./test/alignof.sh
	bash ./test/alignas.sh
	bash ./test/stdalign_header.sh
	bash ./test/stdbool_header.sh
	bash ./test/stdint_header.sh
	bash ./test/inttypes_header.sh
	bash ./test/limits_header.sh
	bash ./test/stddef_header.sh
	bash ./test/string_header.sh
	bash ./test/stdlib_header.sh
	bash ./test/assert_header.sh
	bash ./test/ctype_header.sh
	bash ./test/stdio_header.sh
	bash ./test/noreturn.sh
	bash ./test/inline_function_specifier.sh
	bash ./test/sizeof_alignof_size_t.sh
	bash ./test/sizeof_constraints.sh
	bash ./test/static_assert.sh
	bash ./test/generic_selection.sh
	bash ./test/predefined_func.sh
	bash ./test/gnu_stack.sh
	bash ./test/static_object_alignment.sh
	bash ./test/uint64_fp_conversions.sh
	bash ./test/integer_literals.sh
	bash ./test/signed_specifiers.sh
	bash ./test/type_specifier_combinations.sh
	bash ./test/void_object_constraints.sh
	bash ./test/block_extern_initializer.sh
	bash ./test/char_type_identity.sh
	bash ./test/escape_sequences.sh
	bash ./test/constant_expressions.sh
	bash ./test/compound_literals.sh
	bash ./test/static_integer_initializers.sh
	bash ./test/static_floating_initializers.sh
	bash ./test/static_address_initializers.sh
	bash ./test/aggregate_static_relocations.sh
	bash ./test/union_initializers.sh
	bash ./test/aggregate_initializers.sh
	bash ./test/scalar_brace_initializers.sh
	bash ./test/empty_initializer_constraints.sh
	bash ./test/brace_elision.sh
	bash ./test/array_designators.sh
	bash ./test/nested_designators.sh
	bash ./test/nested_brace_designators.sh
	bash ./test/call_arguments.sh
	bash ./test/record_callback_abi.sh
	bash ./test/record_abi_firewall.sh
	bash ./test/sysv_record_abi.sh
	bash ./test/sysv_sse_record_abi.sh
	bash ./test/sysv_memory_record_abi.sh
	bash ./test/sysv_mixed_union_abi.sh
	bash ./test/string_array_initializers.sh
	bash ./test/nested_string_initializers.sh
	bash ./test/sysv_variadic_callee.sh
	bash ./test/sysv_variadic_record_va_arg.sh
	bash ./test/variadic_record_caller_abi.sh

clean:
	rm -f minicc *.o *~ tmp*

.PHONY: test clean
